# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        Widget.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Widget)
        self.centralwidget.setObjectName("centralwidget")

        # Title
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 30, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        # Login Form
        self.loginForm = QtWidgets.QGroupBox(self.centralwidget)
        self.loginForm.setGeometry(QtCore.QRect(210, 140, 361, 311))
        self.loginForm.setTitle("")
        self.loginForm.setObjectName("loginForm")

        # Email Input (QLineEdit instead of QTextEdit)
        self.emailInput = QtWidgets.QLineEdit(self.loginForm)
        self.emailInput.setGeometry(QtCore.QRect(20, 60, 321, 31))
        self.emailInput.setObjectName("emailInput")
        self.emailInput.setPlaceholderText("Enter your email")

        # Password Input (QLineEdit with Password EchoMode)
        self.passwordInput = QtWidgets.QLineEdit(self.loginForm)
        self.passwordInput.setGeometry(QtCore.QRect(20, 150, 321, 31))
        self.passwordInput.setObjectName("passwordInput")
        self.passwordInput.setPlaceholderText("Enter your password")
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)

        # Labels
        self.label_2 = QtWidgets.QLabel(self.loginForm)
        self.label_2.setGeometry(QtCore.QRect(20, 35, 58, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.loginForm)
        self.label_3.setGeometry(QtCore.QRect(20, 126, 58, 16))
        self.label_3.setObjectName("label_3")

        # Login Button
        self.pushButton = QtWidgets.QPushButton(self.loginForm)
        self.pushButton.setGeometry(QtCore.QRect(120, 210, 111, 41))
        self.pushButton.setObjectName("pushButton")

        Widget.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Widget)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Widget.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Widget)
        self.statusbar.setObjectName("statusbar")
        Widget.setStatusBar(self.statusbar)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

        # -------------------- EXTRA BEHAVIOR --------------------
        # Press Enter in Email → focus Password
        self.emailInput.returnPressed.connect(self.passwordInput.setFocus)

        # Press Enter in Password → click Login button
        self.passwordInput.returnPressed.connect(self.pushButton.click)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "FBR INVOICE TRACKER"))
        self.label_2.setText(_translate("Widget", "Email"))
        self.label_3.setText(_translate("Widget", "Password"))
        self.pushButton.setText(_translate("Widget", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QMainWindow()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
